language: python

cache:
  - pip
  - ccache

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5.1"

install:
  - pip install -U pip wheel
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - pip install chainer
  - pip install nose hacking mock
  - pip install autopep8

script:
  - flake8
  - flake8 --config=.flake8.cython
  - autopep8 -r . --global-config .pep8 --diff | tee check_autopep8
  - test ! -s check_autopep8
  - cd tests
  - nosetests --with-doctest .
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      cd ..;
      READTHEDOCS=True python setup.py develop;
    fi

sudo: false
