batchsize:
valid_batchsize:
valid_trigger:
snapshot_trigger:
log_trigger:
stop_epoch:
seed:

dataset:
  train:
    file:
    name:
    args:
  valid:
    file:
    name:
    args:

model:
  file:
  name:
  args:

loss:
  file:
  name:
  args:

optimizer:
  method:
  args:
  weight_decay:
  lr_drop_ratio:
  lr_drop_trigger:

trainer_extension:
  - dump_graph
  - Evaluator
  - ExponentialShift:
      attr:
      rate:
      init:
      target:
  - LinearShift:
      attr:
      value_range:
      time_range:
  - LogReport:
      keys:
      trigger:
      log_name:
  - observe_lr:
      optimizer_name:
      observation_key:
  - observe_value:
      observation_key:
      target_func:
  - snapshot:
      filename:
  - PlotReport:
      y_keys:
      x_keys:
      trigger:
      file_name:
  - PrintReport:
      entries:
